language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install libjson-glib-dev libsdl1.2-dev libgif-dev gdb
script:
- make travis-deps
- make release RELOCATE_DEPS=true
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
deploy:
  provider: heroku
  strategy: git
  app: imgflo
  on:
    repo: jonnor/imgflo-server
    all_branches: true
    tags: true
  api_key:
    secure: io2ZtKL/3I5T7vYhKQYqWZtv+lCojqvXXH25UZNWq82MuQlLRdPuKUxvFfv2js1zzEMDmFho4OCm5mVWswdaKJsd+uUrf29+z99WJgsMOwJK5nt1TtFJ5VaoeieGsGjbTk7qe0IEU3xMvDIf3Otf9iwpT9JiuzXrbMHp0Cy+LPI=
